__name__ = 'PyHEA'
__version__ = '1.0.0'
__author__ = 'Conrard TETSASSI'
__email__ = 'ConrardGiresse.TetsassiFeugmo@nrc-cnrc.gc.ca'
__maintainer__ = 'Conrard TETSASSI'
__status__ = 'Development'
__doc__ = 'Generative model for HEAs'
